[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "TODO"
version = "0.0.1"
authors = [
  { name="Eric", email="eric@locallyringed.space" }
]
description = "TODO"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
  "pygame",
]

[project.optional-dependencies]
dev = [
  "pytest",
  "pytest-cov",
  "pytest-testmon",
  "pytest-xdist",
]

[template.plugins.default]
src-layout = true

[project.urls]
# Homepage = "TODO"
# Issues = "TODO"

[project.scripts]
# TODO

[tool.hatch.build.targets.wheel]
packages = ["src/backend", "src/frontend"]
